left_dname=Server:
left_nosuch=Niet zo'n virtuele server!
left_users=Beheer gebruikers
left_aliases=Beheer Aliassen
left_edit=Bewerk Virtuele Server
left_generic=Maak Virtuele Server
left_view=Virtuele Server Details
left_virtualmin=Lijst Virtuele Servers
left_databases=Beheer Databases
left_admins=Beheer Extra Admins
left_scripts=Installeer Scripts
left_rename=Verander Domein Naam
left_limits=Bewerk Eigenaar Limieten
left_bw=Bandbreedte Gebruik
left_home=Systeem Informatie
left_home2=Account Informatie
left_pass=Verander Wachtwoord
left_filter=Email Filters
left_autoreply=Automatisch Antwoord
left_forward=Doorsturen Email
left_folders=Beheer Folders
left_addresses=Adres Boek
left_prefs=Mail Voorkeuren
left_login=Login: $1
left_level=Niveau: $1
left_master=Master admin
left_reseller=Reseller
left_single=Mail beheerder
left_user=Server eigenaar
left_extra=Extra admin
left_owner=Systeem eigenaar
left_master2=Cloudmin master admin
left_nodoms=Geen virtuele servers gemaakt.
left_noaccess=U heeft geen toegang tot servers
left_add=Maak Virtuele Server
left_addsub=Maak Sub-Server
left_addalias=Maak Alias Server
left_cmass=Create Van Batch File
left_addsubdom=Maak Sub-Domein
left_tmpl=Systeem Settings
left_tmpl_setting=Systeem Settings
left_tmpl_email=Email Berichten
left_tmpl_ip=Adressen en Netwerken
left_tmpl_check=Limieten en Validatie
left_tmpl_custom=Systeem Wijzigingen
left_create=Toevoegen Servers
left_import=Importeer Server
left_migrate=Migreer Server
left_backup=Backup/Herstel
left_check=Her-controleer Config
left_delete=Verwijder Server
left_search=Zoek:
left_vmsearch=Zoek Virtualmin
left_customlinks=Eigen Links
left_vm2=Lijst Beheer Systemen
left_vm2create=Maak Systeem
left_vm2add=Toevoegen Systeem
left_vm2new=Nieuw Systeem
left_vm2edit=Bewerk Systeem
left_vm2coll=Status
left_vm2doms=Domeinen
left_vm2limits=Limieten
left_vm2ifaces=Interfaces
left_vm2webmin=Open Webmin
left_vm2startup=Starten Systeem
left_vm2shell=Uit te voeren opdrachten
left_vm2reboot=Reboot Systeem
left_vm2shutdown=Uitschakelen Systeem
left_vm2delete=Verwijder Systeem
left_vm2dereg=De-Registreer Systeem
left_vm2refresh=Ververs Status
left_vm2global=Cloudmin Settings
left_vm2status=Status: $1
left_vm2ivirt=Installeer Virtualmin
left_vm2iwebmin=Installeer Webmin
left_vm2recheck=Her-controleer Virtualmin Config
left_vm2image=Maak Systeem Image
left_vm2settings=Systeem Settings
left_direct=Directe Link
left_others=Anders
left_nomore=Er kunnen niet meer servers gemaakt worden

right_header0=Systeem Informatie
right_host=Systeem hostnaam
right_os=Operating systeem
right_login=Ingelogd als
right_realname=Echte naam
right_from=Ingelogd van
right_webmin=Webmin versie
right_usermin=Usermin Versie
right_virtualmin=Virtualmin versie
right_not=Niet geinstalleerd
right_cpu=CPU load gemiddelde
right_loadgraph=$1 (1 min) $2 $3 (5 minuten) $4 $5 (15 minuten) $6
right_real=Echte geheugen
right_virt=Virtueel geheugen
right_procs=Lopende processen
right_disk=Locale disk ruimte
right_used=$1 totaal, $2 gebruikt
right_header1=Virtualmin Informatie
right_virtualminheader=$right_header1
right_fdoms=Virtuele servers
right_fweb=Virtuele websites
right_fssl=SSL websites
right_fdns=DNS domeinen
right_fmail=Mail domeinen
right_fdbs=Databases
right_fusers=Mail/FTP gebruikers
right_faliases=Mail aliassen
right_resellerheader=Reseller Virtuele Servers
right_header4=Virtualmin Disk Gebruik
right_quota10=Alleen top 10 servers laten zien
right_quotamax=Alleen top $1 servers laten zien
right_quotaall=Alle top-level virtuele servers laten zien
right_quotayours=Al uw top-level virtuele servers laten zien
right_out=$1&nbsp;van&nbsp;$2
right_header3=Virtuele Server Informatie
right_dom=Uw server naam
right_subs=Sub-servers
right_aliases=Alias servers
right_of=$1 van $2
right_quota=Disk gebruik en quota
right_bw=Bandbreedte gebruik en limiet
right_bwnone=Bandbreedte gebruik statistieken zijn nog niet verzameld voor een virtuele server.
right_header5=Account Informatie
right_uquota=Disk quota en gebruik
right_header6=Service Status
right_up=Werkend
right_down=Niet Werkend
right_systemheader=Systeem
right_statusheader=Status
right_sysinfoheader=Programma's
right_virtheader=Virtualmin Informatie
right_quotasheader=Quotas
right_ipsheader=IP Adres Locatie
right_restart=Herstart $1
right_defip=(Standaard IP)
right_ip=(Prive IP)
right_reselip=(Reseller $1)
right_sharedip=(Gedeeld IP)
right_ips=$1 virtuele servers
right_iprange=$1 adressen, $2 gebruikt
right_time=Tijd op server
right_kernel=Kernel en CPU
right_kernelon=$1 $2 op $3
right_edit=Configureer deze pagina
right_bwheader=Bandbreedte
right_return=systeem informatie
right_updatesheader=Pakketten Updates
right_upcount=$1 updates aan Virtualmin pakketten zijn beschikbaar. Gebruik de <a href='$2'>Virtualmin Pakketten Update</a> module om ze selectief te installeren.
right_upcount1=Er is 1 ge-update Virtualmin pakket beschikbaar. Gebruik de <a href='$2'>Virtualmin Pakketten Update</a> module om alle beheerde pakketten te zien.
right_upname=Pakketten
right_updesc=Omschrijving
right_upver=Versie
right_upok=Installeer Alle Updates Nu
right_recollect=Ververs systeem informatie
right_overlay=Verander theme
right_pkgupdesc=Pakketten updates
right_upall=Alle <a href='$1'>Virtualmin pakketten</a> zijn in orde.
right_upinst=Er zijn <a href='$2'>$1 optionele Virtualmin pakketten</a> die u kunt installeren.
right_vm2=Cloudmin versie
right_themever=Theme versie
right_vm2serversheader=Cloudmin Beheer Systemen
right_vm2statuses=Systeem Telling Door Status
right_vm2types=Systeem Telling Door Type
right_vserial=Virtualmin serie nummer
right_vkey=Virtualmin licentie sleutel
right_vlcheck=Her-controleer Virtualmin licentie.
right_sserial=Cloudmin serieel nummer
right_skey=Cloudmin licentie sleutel
right_slcheck=Her-controleer Cloudmin licentie.
right_licenceheader=Virtualmin Licenties
right_vmax=Licenties van domeinen
right_vleft=Domeinen over
right_smax=Licentie Virtualmin systemen
right_sused=Systemen geinstalleerd op
right_expiry=Expiratie datum
right_expirydays=Dagen tot expiratie
right_expiryago=$1 dagen geleden!
right_vunlimited=Ongelimiteerd
right_virtdocs=Virtualmin documentatie
right_vm2docs=Cloudmin documentatie
right_header7=Account Functies
right_newfeaturesheader=Nieuwe Virtualmin Extra's
right_newfeaturesheadervm2=Nieuwe Cloudmin Extra's
right_ownerheader=Cloudmin Systeem Eigenaar
right_vm2real=Uw naam
right_vm2email=Uw contact adres
right_vm2one=Uw virtuele systeem
right_status_service=Service
right_status_up=Aan?
right_status_actions=Acties
right_vm2limitsheader=Cloudmin limieten
right_vm2cservers=Huidige systeem telling
right_vm2mservers=Maximum systemen
right_vm2cram=Huidige totale RAM limiet
right_vm2mram=Maximum RAM limiet
right_vm2cdisk=Huidige totale DISK limiet
right_vm2mdisk=Maximum disk limiet
right_vm2ccpu=Huidige totale CPU limiet
right_vm2mcpu=Maximum CPU limiet
right_vm2plan=Account plan

vmain_title=Virtualmin $1 op $2 ($3)
vmain_title2=Virtualmin
mmain_title=Cloudmin $1 op $2 ($3)
mmain_title2=Cloudmin

config_section=Configuratie categorie:
config_change=Verander
config_return=systeem informatie
config_next=Opslaan en Volgende
config_nnext=Volgende
config_nprev=Vorige

edright_title=Systeem Informatie Configuratie
edright_header=Virtualmin systeem informatie pagina settings
edright_sects=Zichtbare informatie
edright_alt=Aanvankelijke rechter-frame inhoud
edright_altdef=Reguliere systeem informatie
edright_global=Toevoegen aan alle gebruikers?
edright_nowebmin=Laat de Webmin tab zien op het linker menu?
edright_others=Alleen voor master administrator
edright_alturl=Laat URL zien
edright_err=Mislukt om de systeem informatie pagina configuratie op te slaan
edright_ealt=Ontbrekende of ongeldige URL
edright_dom=Standaard virtuele server
edright_server=Standaard Cloudmin systeem
edright_first=&lt;Eerste in lijst&gt;
edright_qsort=Sorteer quota en bandbreedte gebruik met
edright_qsort1=Percentage van limiet
edright_qsort0=Bytes gebruikt
edright_qshow=Laat quotas en bandbreedte gebruik zien als
edright_max=Maximum servers om te laten zien
edright_emax=Maximum servers moet een getal zijn groter dan nul
edright_deftab=Standaard mode op linker menu
edright_tab1=Welke als eerste is
edright_virtualmin=Virtualmin
edright_vm2=Cloudmin
edright_webmin=Webmin
edright_fsize=Linker frame breedte
edright_fsizedef=Beslis automatisch
edright_pixels=pixels
edright_efsize=Ontbrekende of ongeldige linker frame breedte in pixels

has_virtualmin=Virtualmin
has_mail=Mail
has_vm2=Cloudmin
has_webmin=Webmin
has_usermin=Usermin

overlay_title=Verander Theme
overlay_desc=Op deze pagina kunt u een andere theme kiezen, waarvan de kleuren kunnen worden verandert plus de iconen en layout van de Virtualmin gebruiker interface.
overlay_msg=Verander theme overlay naar:
overlay_ok=Verander Nu
overlay_none=Niets - gebruik standaard kleuren en iconen
overlay_refresh=Verversen van de Virtualmin gebruiker interface ..
overlay_done=.. klaar
overlay_euser=Mislukt om de details van de huidige gebruiker te verkrijgen!
overlay_webmin=Herladen van de Webmin configuratie ..
